In [2]:
import numpy as np

In [3]:
arr=[1,2,4,5,6,78,90,89,90]
np_arr=np.array([arr])

In [4]:
np_arr

array([[ 1,  2,  4,  5,  6, 78, 90, 89, 90]])

In [5]:
# Create a 2D Array
np_arr.shape

(1, 9)

In [6]:
# TO check dimension
np_arr.ndim

2

In [7]:
# Create a array having 2 rows and 4 Columns 
k=[np.random.randn(4),np.random.randn(4)]
k

[array([ 1.34679962, -0.68133704, -0.42586471,  0.72367633]),
 array([ 0.27784495, -0.2823416 , -1.01197703,  0.44457065])]

In [8]:
# Create a 3-D Array
k=[[np.random.randn(4),np.random.randn(4)]]
k=np.array(k)
print(k.ndim)
print(k.shape)
print(k)

3
(1, 2, 4)
[[[ 0.47483693  0.0637399   0.70463909  0.1119022 ]
  [-0.21879195  1.48260714 -1.18860542 -0.20809103]]]


In [9]:
# Create a 2 2-D Arrays 3 Rows 4 columns
ls=[[[np.random.randint(4),np.random.randint(4),np.random.randint(4)]],[[np.random.randint(4),np.random.randint(4),np.random.randint(4)]]]
k=np.array(ls)
print(k.ndim)
print(k.shape)
print(k)

3
(2, 1, 3)
[[[2 0 3]]

 [[3 0 0]]]


In [10]:
# 1-D Array Total no. of elements = no. of elements
# 2-D Array Total no. of elements = no. of 1d Arrays
# 3-D Array Total no. of elements = no. of 2d Arrays
# 4-D Array Total no. of elements = no. of 3d Arrays
# nd Array Total no. of elements = no. of n-1 Arrays


In [11]:
arr=[[2,4,6,8],[2,4,6,8],[2,4,6,8]]
arr

[[2, 4, 6, 8], [2, 4, 6, 8], [2, 4, 6, 8]]

In [12]:
arr=np.array(arr)
arr.sum()

60

In [13]:
arr.sum(axis=0)
# axis -> 0 Column Wise

array([ 6, 12, 18, 24])

In [14]:
arr.sum(axis=1)
# axis -> 1 Row Wise 

array([20, 20, 20])

In [15]:
arr.max()

8

In [17]:
print("Maximum Element in Column Wise ",arr.max(axis=0))
print("Minimum Element in Column Wise ",arr.min(axis=0))
print("Average Element in Column Wise ",arr.mean(axis=0))

print("Maximum Element in Column Wise ",arr.max(axis=1))
print("Minimum Element in Column Wise ",arr.min(axis=1))
print("Average Element in Column Wise ",arr.mean(axis=1))


Maximum Element in Column Wise  [2 4 6 8]
Minimum Element in Column Wise  [2 4 6 8]
Average Element in Column Wise  [2. 4. 6. 8.]
Maximum Element in Column Wise  [8 8 8]
Minimum Element in Column Wise  [2 2 2]
Average Element in Column Wise  [5. 5. 5.]


In [18]:
# Find the Index at what index it is present 
arr.argmax()

3

In [19]:
arr.argmin()

0

In [21]:
#create a Zero Matrix 
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [22]:
type(z)

numpy.ndarray

In [23]:
# TO know the type of elements 
z.dtype

dtype('float64')

In [24]:
type(z),z.dtype

(numpy.ndarray, dtype('float64'))

In [25]:
# 1-d Array -> Vector
# 2-d Arrays -> Matrix
# 3-d Arrays -> Tensors


In [27]:
z1=np.zeros((2,5))
print(z1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
z1=np.zeros((2,5),dtype=int)
print(z1)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [31]:
z2=np.ones((2,5),dtype=int)
print(z2)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [34]:
z3=np.zeros((2,5),dtype=int)+5
print(z3)

# or

z3=np.ones((2,5),dtype=int)*5
print(z3)

[[5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]]


In [35]:
# Create a Diagonal or  
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [38]:
# identity Matrix
np.eye(5, dtype=int)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [56]:
x=np.arange(0,10,2)
print(x)


[0 2 4 6 8]


In [46]:
np.linspace(10,2)

array([10.        ,  9.83673469,  9.67346939,  9.51020408,  9.34693878,
        9.18367347,  9.02040816,  8.85714286,  8.69387755,  8.53061224,
        8.36734694,  8.20408163,  8.04081633,  7.87755102,  7.71428571,
        7.55102041,  7.3877551 ,  7.2244898 ,  7.06122449,  6.89795918,
        6.73469388,  6.57142857,  6.40816327,  6.24489796,  6.08163265,
        5.91836735,  5.75510204,  5.59183673,  5.42857143,  5.26530612,
        5.10204082,  4.93877551,  4.7755102 ,  4.6122449 ,  4.44897959,
        4.28571429,  4.12244898,  3.95918367,  3.79591837,  3.63265306,
        3.46938776,  3.30612245,  3.14285714,  2.97959184,  2.81632653,
        2.65306122,  2.48979592,  2.32653061,  2.16326531,  2.        ])

In [ ]:
# Write a Program to sort 2000 elements using 