- Numpy arrays essentially come in two flavors: vectors and matrices. <br>
- Vectors are strictly I-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


### <span style="font-family: 'Times New Roman', Times, serif;">Welcome to NumPy Arrays</span>

## Advantages of using Numpy array over Python Lists
- **NumPy arrays are implemented in C** and allow for efficient storage and manipulation of data, enabling faster computations due to vectorization. This means operations on NumPy arrays can be performed using highly optimized C code, bypassing the slower Python loop mechanics.
- **NumPy arrays consume less memory than Python lists.** This is because NumPy directly stores data in a contiguous block of memory, reducing overhead. A Python list, on the other hand, stores pointers to objects scattered across memory.
- **NumPy provides an array interface with operations like element-wise addition, multiplication, and complex operations (e.g., matrix multiplication)** directly supported, without the need for explicit Python loops.
- **NumPy offers a comprehensive set of mathematical functions for operations on arrays, including statistical, algebraic, and Fourier transform operations**, that are highly optimized for performance.
- **NumPy arrays are homogeneous, meaning they store elements of the same data type, allowing for more efficient and predictable operations.**
-  **NumPy allows specifying precise data types (e.g., float64, int32)**, offering control over the precision and size of the data stored, which is critical for scientific computing and memory efficiency.

In [2]:
my_list=[1,2,3]

In [3]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# Rows, Columns
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# Return evenly spaced numbers over a specified interval.
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [19]:
# Identity Matrix - Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.10862281, 0.73034407, 0.82092559, 0.63982642, 0.73749245])

In [22]:
# Random values in a given shape
np.random.rand(5,5)

array([[0.63719637, 0.29930771, 0.11791009, 0.99237849, 0.09787749],
       [0.8639181 , 0.20966057, 0.12933443, 0.83568993, 0.19675307],
       [0.06865847, 0.01249801, 0.26229767, 0.68313811, 0.9766811 ],
       [0.34829704, 0.3568409 , 0.7037179 , 0.03841142, 0.87011313],
       [0.73834157, 0.72048959, 0.933203  , 0.62895632, 0.51382714]])

In [24]:
# Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(4,4)

array([[-1.24581313,  1.08398273,  1.20444262,  0.52034785],
       [-0.32161763, -0.52145807, -1.00950478,  0.5263389 ],
       [ 0.78135022, -0.87644108, -1.08746569,  0.6056958 ],
       [-0.6692526 ,  1.1533492 ,  0.33290791,  1.02776169]])

In [34]:
# Return random integers from `low` (inclusive) to `high` (exclusive). with given shape
np.random.randint(1,100,10)

array([ 2, 91, 30, 52, 12, 89, 33, 50, 77, 58])

In [38]:
arr=np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [66]:
ranarr=np.random.randint(0,50,10)
print(ranarr)

[12 38 26 40 40 37  3 47 17  1]


In [51]:
# Returns an array containing the same data with a new shape.
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
print(ranarr.max())
print(ranarr.min())

49
10


In [67]:
print(ranarr.max())
# To find the Indesx value of Minimum value argmin()
print("index value of {} is {}".format(ranarr.max(),ranarr.argmax()))
# To find the Index value of Maxmimum Value argmax()
print(ranarr.min())

47
index value of 47 is 7
1


In [74]:
print(arr.reshape(5,5).shape)
print(ranarr)
print("Shape of the Vector is {}".format(arr.shape))
print("Shape of the Vector is {}".format(ranarr.shape))

(5, 5)
[12 38 26 40 40 37  3 47 17  1]
Shape of the Vector is (25,)
Shape of the Vector is (10,)


In [75]:
"""
A numpy array is homogeneous, and contains elements described by a dtype object. 
A dtype object can be constructed from different
combinations of fundamental numeric types.
"""
arr.dtype

dtype('int32')

In [77]:
from numpy.random import randint
randint(2,10)

3

## Summary
- np.array(my_list)
    - Creates a NumPy array from my_list.

- np.arange(0,10)
    - Generates an array with values from 0 up to (but not including) 10.

- np.zeros((5,5))
    - Creates a 5x5 array filled with zeros.

- np.linspace(0,3,10)
    - Generates 10 evenly spaced values from 0 to 3.

- np.eye(4)
    - Creates a 4x4 identity matrix (diagonal of 1s).

- np.random.rand(5)
    - Produces an array of 5 random samples from a uniform distribution over [0, 1).

- np.random.randn(4,4)
    - Generates a 4x4 array of samples from the standard normal (Gaussian) distribution.

- np.random.randint(1,100,10)
    - Returns 10 random integers from 1 (inclusive) to 100 (exclusive).

- arr.reshape(5,5)
    - Reshapes an existing array into a 5x5 matrix.

- ranarr.max()
    - Finds the maximum value in ranarr.

- ranarr.min()
    - Determines the minimum value in ranarr.

- ranarr.argmax()
    - Retrieves the index of the maximum value in ranarr.

- arr.dtype
    - Returns the data type of the elements in arr.

## Numpy Indexing and Selection

In [78]:
# Insert all the elements from 0-10
arr=np.arange(0,11)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr[8]

8

In [81]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [82]:
arr[1:5]

array([1, 2, 3, 4])

In [83]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [86]:
# From given point to end of the list
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
# One of the special Feature of Numpy Arrays is Broadcasting
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [88]:
arr=np.arange(0,11)

In [89]:
slice_of_array=arr[0:6]
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [90]:
slice_of_array[:]=99

In [92]:
arr
# Notice here pass by reference is performed!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [93]:
# If we want a copy and not a view/reference then we need to use a copy method
arr_copy=arr.copy()

In [97]:
arr=np.arange(0,11)
slice_of_array=arr_copy[0:5]
slice_of_array[:]=99

In [98]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
# Create a 2-D Array
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [108]:
# Double Bracket Representation for 2-D Arrays
print(arr_2d[0][0])
# Single Bracket Representation for 2-D Arrays
print(arr_2d[0,0])

5
5


In [104]:
for i in arr_2d:
    for j in i:
        print(f"{j} ")
    print("\n")

5 
10 
15 


20 
25 
30 


35 
40 
45 




In [109]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [112]:
# Conditional Selection
arr=np.arange(1,11)

In [113]:
bool_arr=arr>5

In [114]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [131]:
addendum=arr+5
add=sum(arr)
print(add)
print(arr)
print(arr[::-1])
# arr.reshape(5,2).diagonal()

55
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [116]:
addendum

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [133]:
# Epitome for Conditional Selection!
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [134]:
arr[arr<3]

array([1, 2])

In [136]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [140]:
# Grab 24,25,26 using slicing notation
arr_2d[2:3,4:7]


array([[24, 25, 26]])

## Numpy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions

In [141]:
arr=np.arange(0,11)

In [142]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
# Add two arrays together element by element
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [145]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [150]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [147]:
# Note when performing 0/0 Python will give ZeroDivisionError Error 
0/0

ZeroDivisionError: division by zero

In [152]:
# How ever Numpy tackles the problem seamlessly 
# Here first element is 0, it will just give a warning and place nan (Not a Number)
arr/arr

C:\Users\KIIT\AppData\Local\Temp\ipykernel_28480\480959263.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [153]:

1/arr

C:\Users\KIIT\AppData\Local\Temp\ipykernel_28480\929111479.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [154]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [155]:
# Universal Array Operations
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [156]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [157]:
np.max(arr)

10

In [158]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [159]:
np.log(arr)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_28480\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

[Numpy Mathematical Docs Reference](https://numpy.org/doc/stable/reference/routines.math.html)