In [1]:
import numpy as np

In [11]:
# Element-wise addition of 2 numpy arrays
x=np.array(np.random.randint(1,10,5))
y=np.array(np.random.randint(1,10,5))

print(x)
print(y)
print(x+y)

[6 2 1 1 5]
[6 7 8 6 3]
[12  9  9  7  8]


In [12]:
# Multiplying a matrix (numpy array) by a scalar
print(x*y)

[36 14  8  6 15]


In [14]:
# Identity Matrix
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
# Array re-dimensioning
print(x.ndim)
x.reshape(1,5,1).ndim


1


3

In [23]:
# Array datatype conversion
print(x.dtype)
print(x.astype('float32').dtype)

float32


In [30]:
# Obtaining Boolean Array from Binary Array
x=np.random.randint(0,2,10)
x
y=[True,False]
y=np.array(y)
y.dtype
print(x.astype('bool'))

[ True  True  True False False  True  True False False  True]


In [34]:
# Horizontal Stacking of Numpy Arrays
z1=np.array(np.random.randint(1,10,5))
z2=np.array(np.random.randint(1,10,5))

print(z1)
print(z2)
print(np.hstack((z1,z2)))

[6 2 8 9 8]
[1 5 2 5 8]
[6 2 8 9 8 1 5 2 5 8]


In [35]:
# Vertical Stacking of Numpy Arrays
print(np.vstack((z1,z2)))

[[6 2 8 9 8]
 [1 5 2 5 8]]


In [39]:
# Custom Sequence Generation
tv=[]
for i in range(0,101,2):
    tv.append(i)
print(tv)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [44]:
import numpy as np

z3 = [5, 6, 7, 8]
z4 = [6, 7, 8, 9]
x8 = np.array(z3)
x9 = np.array(z4)

common_elements = np.intersect1d(x8, x9)

for element in common_elements:
    index = np.where(x8 == element)
    print(f"Element {element} found at index {index[0][0]} in the first array")

matching_indices = np.where(x8 == x9)[0]
print("Indices where x8 == x9:", matching_indices)


Element 6 found at index 1 in the first array
Element 7 found at index 2 in the first array
Element 8 found at index 3 in the first array
Indices where x8 == x9: []


In [45]:
# EXERCISE 11 - Generation of given count of equally spaced numbers within a specified range
import numpy as np

# Generating 5 equally spaced numbers from 0 to 100
numbers = np.linspace(0, 100, 5)
print("Equally spaced numbers:", numbers)


Equally spaced numbers: [  0.  25.  50.  75. 100.]


In [46]:
# EXERCISE 12 - Matrix Generation with one particular value
import numpy as np

# Creating a 2x3 matrix with all values equal to 5
matrix = np.full((2, 3), 5)
print("Matrix filled with 5s:", matrix)


Matrix filled with 5s: [[5 5 5]
 [5 5 5]]


In [47]:
# Array Generation by repeatition of a small array across each dimension
import numpy as np

small_array = np.array([[1, 2], [3, 4]])
repeated_array = np.tile(small_array, (10, 10))  # Repeat 10 times in each dimension
print("Repeated array:\n", repeated_array)


Repeated array:
 [[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]]


In [48]:
# EXERCISE 14 - Array Generation of random integers within a specified range
array_random_integers = np.random.randint(0, 10, (5, 5))
print("5x5 array of random integers:\n", array_random_integers)


5x5 array of random integers:
 [[6 4 2 6 1]
 [5 3 3 5 9]
 [9 5 5 1 4]
 [9 4 0 5 6]
 [7 6 5 8 9]]


In [54]:
# EXERCISE 15 - Array Generation of random numbers following normal distribution
array_normal_dist = np.random.randn(3, 3)  # Standard normal distribution
print("3x3 array of random numbers (normal distribution):\n", array_normal_dist)


3x3 array of random numbers (normal distribution):
 [[ 0.55626968  0.00839072  1.20749429]
 [ 0.94631815 -2.70501588  0.08683233]
 [ 1.13100094 -1.27429991  0.40630798]]


In [55]:
# EXERCISE 16 - Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print("Product of A and B:\n", product)


Product of A and B:
 [[19 22]
 [43 50]]


In [56]:
# EXERCISE 17 - Matrix Transpose
matrix = np.array([[1, 2], [3, 4], [5, 6]])
transpose_matrix = matrix.T
print("Transpose of the matrix:\n", transpose_matrix)


Transpose of the matrix:
 [[1 3 5]
 [2 4 6]]


In [52]:
# EXERCISE 18 - Sine of an Angle (in radians)
angles = np.array([0, np.pi/2, np.pi])
sine_values = np.sin(angles)
print("Sine of angles:\n", sine_values)


In [57]:
# EXERCISE 19 - Cosine Similarity
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
cosine_similarity = np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))
print("Cosine similarity:", cosine_similarity)


Cosine similarity: 0.9746318461970762


In [58]:
# EXERCISE 20 - Generating the array element indexes such that the array elements appear in ascending order
array = np.array([4, 2, 3, 1, 5])
sorted_indices = np.argsort(array)
print("Indices to sort array:", sorted_indices)


Indices to sort array: [3 1 2 0 4]


In [63]:
#  Exercise 1. Import numpy as np and see the version
print(np.__version__)
#  Exercise 2. How to create a 1D array?
arr=[1,2,3,4]
print(type(np.array(arr)))
#  Exercise 3. How to create a boolean array?

bool_array = np.array([True, False, True, False])
print("Boolean array:", bool_array)

numbers = np.array([2, 6, 7, 3, 8, 4])
condition_array = numbers > 5  # This will check if each number is greater than 5
print("Condition-based Boolean array:", condition_array)

#  Exercise 4. How to extract items that satisfy a given
# condition from 1D array?


array_1d = np.array([1, 2, 6, 7, 5, 3, 8, 9])

condition = array_1d > 5
extracted_items = array_1d[condition]
print("Extracted items:", extracted_items)

#  Exercise 5. How to replace items that satisfy a condition with another value in numpy array?


array_1d = np.array([1, 2, 6, 7, 5, 3, 8, 9])

condition = array_1d > 5

array_1d[condition] = 10
print("Array after replacement:", array_1d)


1.24.3
<class 'numpy.ndarray'>
Boolean array: [ True False  True False]
Condition-based Boolean array: [False  True  True False  True False]
Extracted items: [6 7 8 9]
Array after replacement: [ 1  2 10 10  5  3 10 10]
