In [2]:
import numpy as np

In [3]:
# Element-wise addition of 2 numpy arrays
x=np.array(np.random.randint(1,10,5))
y=np.array(np.random.randint(1,10,5))

print(x)
print(y)
print(x+y)

[6 5 5 4 1]
[4 9 1 9 2]
[10 14  6 13  3]


In [4]:
# Multiplying a matrix (numpy array) by a scalar
print(x*y)

[24 45  5 36  2]


In [5]:
# Identity Matrix
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [6]:
# Array re-dimensioning
print(x.ndim)
x.reshape(1,5,1).ndim


1


3

In [7]:
# Array datatype conversion
print(x.dtype)
print(x.astype('float32').dtype)

int32
float32


In [8]:
# Obtaining Boolean Array from Binary Array
x=np.random.randint(0,2,10)
x
y=[True,False]
y=np.array(y)
y.dtype
print(x.astype('bool'))

[False False False False False  True False False  True False]


In [9]:
# Horizontal Stacking of Numpy Arrays
z1=np.array(np.random.randint(1,10,5))
z2=np.array(np.random.randint(1,10,5))

print(z1)
print(z2)
print(np.hstack((z1,z2)))

[8 9 9 7 6]
[1 4 3 6 8]
[8 9 9 7 6 1 4 3 6 8]


In [10]:
# Vertical Stacking of Numpy Arrays
print(np.vstack((z1,z2)))

[[8 9 9 7 6]
 [1 4 3 6 8]]


In [11]:
# Custom Sequence Generation
tv=[]
for i in range(0,101,2):
    tv.append(i)
print(tv)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [12]:
import numpy as np

z3 = [5, 6, 7, 8]
z4 = [6, 7, 8, 9]
x8 = np.array(z3)
x9 = np.array(z4)

common_elements = np.intersect1d(x8, x9)

for element in common_elements:
    index = np.where(x8 == element)
    print(f"Element {element} found at index {index[0][0]} in the first array")

matching_indices = np.where(x8 == x9)[0]
print("Indices where x8 == x9:", matching_indices)


Element 6 found at index 1 in the first array
Element 7 found at index 2 in the first array
Element 8 found at index 3 in the first array
Indices where x8 == x9: []


In [13]:
# EXERCISE 11 - Generation of given count of equally spaced numbers within a specified range
import numpy as np

# Generating 5 equally spaced numbers from 0 to 100
numbers = np.linspace(0, 100, 5)
print("Equally spaced numbers:", numbers)


Equally spaced numbers: [  0.  25.  50.  75. 100.]


In [14]:
# EXERCISE 12 - Matrix Generation with one particular value
import numpy as np

# Creating a 2x3 matrix with all values equal to 5
matrix = np.full((2, 3), 5)
print("Matrix filled with 5s:", matrix)


Matrix filled with 5s: [[5 5 5]
 [5 5 5]]


In [15]:
# Array Generation by repeatition of a small array across each dimension
import numpy as np

small_array = np.array([[1, 2], [3, 4]])
repeated_array = np.tile(small_array, (10, 10))  # Repeat 10 times in each dimension
print("Repeated array:\n", repeated_array)


Repeated array:
 [[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]]


In [16]:
# EXERCISE 14 - Array Generation of random integers within a specified range
array_random_integers = np.random.randint(0, 10, (5, 5))
print("5x5 array of random integers:\n", array_random_integers)


5x5 array of random integers:
 [[4 7 3 0 2]
 [5 5 2 5 1]
 [6 9 1 6 5]
 [1 8 2 5 9]
 [6 0 6 6 0]]


In [17]:
# EXERCISE 15 - Array Generation of random numbers following normal distribution
array_normal_dist = np.random.randn(3, 3)  # Standard normal distribution
print("3x3 array of random numbers (normal distribution):\n", array_normal_dist)


3x3 array of random numbers (normal distribution):
 [[-0.00795682  1.02630479 -1.32558115]
 [ 0.00953438 -0.09226682  0.49206101]
 [-0.81932893  0.1115017   2.04504775]]


In [18]:
# EXERCISE 16 - Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print("Product of A and B:\n", product)


Product of A and B:
 [[19 22]
 [43 50]]


In [19]:
# EXERCISE 17 - Matrix Transpose
matrix = np.array([[1, 2], [3, 4], [5, 6]])
transpose_matrix = matrix.T
print("Transpose of the matrix:\n", transpose_matrix)


Transpose of the matrix:
 [[1 3 5]
 [2 4 6]]


In [20]:
# EXERCISE 18 - Sine of an Angle (in radians)
angles = np.array([0, np.pi/2, np.pi])
sine_values = np.sin(angles)
print("Sine of angles:\n", sine_values)


Sine of angles:
 [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [21]:
# EXERCISE 19 - Cosine Similarity
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
cosine_similarity = np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))
print("Cosine similarity:", cosine_similarity)


Cosine similarity: 0.9746318461970762


In [22]:
# EXERCISE 20 - Generating the array element indexes such that the array elements appear in ascending order
array = np.array([4, 2, 3, 1, 5])
sorted_indices = np.argsort(array)
print("Indices to sort array:", sorted_indices)


Indices to sort array: [3 1 2 0 4]


In [23]:
#  Exercise 1. Import numpy as np and see the version
print(np.__version__)
#  Exercise 2. How to create a 1D array?
arr=[1,2,3,4]
print(type(np.array(arr)))
#  Exercise 3. How to create a boolean array?

bool_array = np.array([True, False, True, False])
print("Boolean array:", bool_array)

numbers = np.array([2, 6, 7, 3, 8, 4])
condition_array = numbers > 5  # This will check if each number is greater than 5
print("Condition-based Boolean array:", condition_array)

#  Exercise 4. How to extract items that satisfy a given
# condition from 1D array?


array_1d = np.array([1, 2, 6, 7, 5, 3, 8, 9])

condition = array_1d > 5
extracted_items = array_1d[condition]
print("Extracted items:", extracted_items)

#  Exercise 5. How to replace items that satisfy a condition with another value in numpy array?


array_1d = np.array([1, 2, 6, 7, 5, 3, 8, 9])

condition = array_1d > 5

array_1d[condition] = 10
print("Array after replacement:", array_1d)


1.24.3
<class 'numpy.ndarray'>
Boolean array: [ True False  True False]
Condition-based Boolean array: [False  True  True False  True False]
Extracted items: [6 7 8 9]
Array after replacement: [ 1  2 10 10  5  3 10 10]


In [27]:
arr=np.arange(10)
arr
k=arr

In [28]:
k[0]=10

In [29]:
k

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [30]:
arr

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [31]:
k=arr.copy()
k[0]=5


In [32]:
k

array([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [41]:
arr
k
np.
hstack([arr,k])

SyntaxError: invalid syntax (1156282808.py, line 3)

In [40]:
import seaborn as sns
k=np.arange(10)
sns.displot(k,kde=True)

c:\Users\KIIT\anaconda3\Lib\site-packages\seaborn\axisgrid.py:118: UserWarning: The figure layout has changed to tight
  self._figure.tight_layout(*args, **kwargs)


In [44]:
arr=np.arange(3)+1
np.tile(arr,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
np.repeat(arr,3)
np.r_[np.repeat(arr,3),np.tile(arr,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [50]:
a=np.arange(10)
b=np.arange(10)+1

In [58]:
a,b

k=[set(a) & set(b)]
k

[{1, 2, 3, 4, 5, 6, 7, 8, 9}]

In [57]:
# import pandas as pd
# df=pd.DataFrame([a,b])
# # lambda x,y,i: x[i]==y[i]
# df.apply(lambda x,y,i: x[i]==y[i])

TypeError: <lambda>() missing 2 required positional arguments: 'y' and 'i'

In [59]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.902, 0.029, 0.532],
       [0.608, 0.15 , 0.864],
       [0.1  , 0.369, 0.299],
       [0.545, 0.811, 0.964],
       [0.504, 0.581, 0.977]])

In [73]:
a = np.arange(15)
np.set_printoptions(threshold=13)
print(a)

[ 0  1  2 ... 12 13 14]


In [77]:
from sklearn.datasets import load_iris
import numpy as np

# Load the iris dataset
iris = load_iris()

# Access the data and target
X = iris.data  # Features (sepal length, sepal width, petal length, petal width)
y = iris.target  # Target (species)
feature_names = iris.feature_names  # Feature names
target_names = iris.target_names  # Target names (species names)

# Convert the data to a structured numpy array
data_types = [(feature_name, np.float64) for feature_name in feature_names]
data_types.append(('species', 'U20'))
iris_data = np.zeros(X.shape[0], dtype=data_types)

# Assign the features and targets to the structured array
for i, feature_name in enumerate(feature_names):
    iris_data[feature_name] = X[:, i]
iris_data['species'] = np.array([target_names[target] for target in y])

In [78]:
iris_data

array([(5.1, 3.5, 1.4, 0.2, 'setosa'), (4.9, 3. , 1.4, 0.2, 'setosa'),
       (4.7, 3.2, 1.3, 0.2, 'setosa'), ...,
       (6.5, 3. , 5.2, 2. , 'virginica'),
       (6.2, 3.4, 5.4, 2.3, 'virginica'),
       (5.9, 3. , 5.1, 1.8, 'virginica')],
      dtype=[('sepal length (cm)', '<f8'), ('sepal width (cm)', '<f8'), ('petal length (cm)', '<f8'), ('petal width (cm)', '<f8'), ('species', '<U20')])

In [81]:
import numpy as np

def softmax(x):
    """Compute the softmax of vector x."""
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    return exp_x / sum_exp_x

# Example input vectors
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute softmax scores along the rows (axis=1)
softmax_scores = softmax(x)

print("Input vectors:")
print(X)
print("\nSoftmax scores:")
print(softmax_scores.sum())
print(softmax_scores)

Input vectors:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Softmax scores:
0.9999999999999999
[0.074 0.074 0.074 0.074 0.074 0.202 0.074 0.074 0.202 0.074]
